# Financial Sentiment Analysis
 <h5>WMG9B7-15 - Artificial Intelligence & Deep Learning</h5>
 <h5>u5696284</h5>
 <h5>
 A sentiment analysis using Twitter Financial News dataset
 </h5>

### Phase 0: Setup & Environment

In [1]:
%pip install ipykernel numpy pandas matplotlib scikit-learn transformers datasets evaluate torch ipywidgets -q

Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import random
import torch
from datasets import load_dataset

In [3]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

### Phase 1: Data Loading & Exploration

In [4]:
ds = load_dataset("zeroshot/twitter-financial-news-sentiment")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
print(ds)
# Splitting ds into training and testing dataset
train_data = ds['train']
test_data = ds['validation']

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 9543
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2388
    })
})

In [6]:
# Converting train and test python dict to pandas dataframe
train_df = pd.DataFrame(train_data)
test_df = pd.DataFrame(test_data)

In [7]:
print(train_df.shape)
print(test_df.shape)

(9543, 2)
(2388, 2)

In [8]:
train_df.head()

                                                text  label
0  $BYND - JPMorgan reels in expectations on Beyo...      0
1  $CCL $RCL - Nomura points to bookings weakness...      0
2  $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3  $ESS: BTIG Research cuts to Neutral https://t....      0
4  $FNKO - Funko slides after Piper Jaffray PT cu...      0

In [9]:
train_df.tail()

                                                   text  label
9538  The Week's Gainers and Losers on the Stoxx Eur...      2
9539  Tupperware Brands among consumer gainers; Unil...      2
9540  vTv Therapeutics leads healthcare gainers; Myo...      2
9541    WORK, XPO, PYX and AMKR among after hour movers      2
9542             YNDX, I, QD and OESX among tech movers      2

In [10]:
train_df.dtypes # Checking type of data

text       str
label    int64
dtype: object

In [11]:
train_df.count()

text     9543
label    9543
dtype: int64

In [12]:
train_df.duplicated().sum()  # Returns number of duplicate rows

np.int64(0)

In [13]:
train_df.isna().sum() # Checking for missing values

text     0
label    0
dtype: int64

In [14]:
train_df["label"].value_counts()

label
2    6178
1    1923
0    1442
Name: count, dtype: int64